package registry

import (
	"os"
	"path/filepath"
	"testing"
)

func TestLockfileRoundTrip(t *testing.T) {
	path := filepath.Join(t.TempDir(), "datasplice.lock")

	l := &Lockfile{Entries: map[Ref]string{
		{Host: "github.com", Path: "myorg/datasplice-zendesk", Version: "v0.2.0"}: "5rxk2n8",
		{Host: "github.com", Path: "a/b", Version: "v1.0.0"}:                      "9qlm4kp",
	}}
	if err := l.Save(path); err != nil {
		t.Fatalf("Save: %v", err)
	}

	got, err := LoadLockfile(path)
	if err != nil {
		t.Fatalf("LoadLockfile: %v", err)
	}

	for ref, hash := range l.Entries {
		gotHash, ok := got.Hash(ref)
		if !ok || gotHash != hash {
			t.Errorf("Hash(%s) = %q, %v; want %q, true", ref, gotHash, ok, hash)
		}
	}
}

func TestLockfileMatchesDocumentedFormat(t *testing.T) {
	path := filepath.Join(t.TempDir(), "datasplice.lock")
	l := &Lockfile{Entries: map[Ref]string{
		{Host: "github.com", Path: "myorg/datasplice-zendesk", Version: "v0.2.0"}: "5rxk2n8",
	}}
	if err := l.Save(path); err != nil {
		t.Fatalf("Save: %v", err)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}

	want := "# Generated by datasplice. Commit this file.\nversion 1\n\ngithub.com/myorg/datasplice-zendesk v0.2.0 sha256:5rxk2n8\n"
	if string(data) != want {
		t.Fatalf("lockfile =\n%s\nwant\n%s", data, want)
	}
}

func TestLoadLockfileMissingFileIsEmpty(t *testing.T) {
	l, err := LoadLockfile(filepath.Join(t.TempDir(), "nope.lock"))
	if err != nil {
		t.Fatalf("LoadLockfile: %v", err)
	}

	if len(l.Entries) != 0 {
		t.Fatalf("expected an empty lockfile, got %v", l.Entries)
	}
}

func TestLoadLockfileRejectsMalformedLines(t *testing.T) {
	cases := []string{
		"version 2\n",
		"version 1\n\ngithub.com/org/repo v1 not-sha256\n",
		"version 1\n\ngithub.com/org/repo v1 sha256:abc extra\n",
		"version 1\n\nnohostpath v1 sha256:abc\n",
	}

	for _, body := range cases {
		path := filepath.Join(t.TempDir(), "datasplice.lock")
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}

		if _, err := LoadLockfile(path); err == nil {
			t.Errorf("LoadLockfile(%q) succeeded, want an error", body)
		}
	}
}
