package registry

import (
	"bufio"
	"fmt"
	"os"
	"sort"
	"strings"
)

// LockFile is datasplice.lock — a flow-level file, same convention as
// main.yaml/secrets.yaml: a bare relative name, read from whatever
// directory the CLI is run in.
const LockFile = "datasplice.lock"

const lockVersion = "version 1"

// Lockfile pins every third-party ref to a content hash. See
// docs/getting-started/file-structure.md "datasplice.lock" for the
// on-disk format this reads and writes byte-for-byte:
//
//	version 1
//
//	github.com/myorg/datasplice-zendesk v0.2.0 sha256:5rXk2N8vQm...
type Lockfile struct {
	// Entries is ref (without the leading host, matching the documented
	// format's "<module> <version> sha256:<hash>") -> sha256 hash.
	Entries map[Ref]string
}

// LoadLockfile returns an empty Lockfile if path doesn't exist — no
// lockfile just means nothing has been `get`-ed yet.
func LoadLockfile(path string) (*Lockfile, error) {
	f, err := os.Open(path)
	if err != nil {
		if os.IsNotExist(err) {
			return &Lockfile{Entries: map[Ref]string{}}, nil
		}

		return nil, fmt.Errorf("reading %s: %w", path, err)
	}
	defer func() { _ = f.Close() }()

	l := &Lockfile{Entries: map[Ref]string{}}
	sc := bufio.NewScanner(f)
	lineNo := 0
	sawVersion := false

	for sc.Scan() {
		lineNo++
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		if !sawVersion {
			if line != lockVersion {
				return nil, fmt.Errorf("%s:%d: expected %q, got %q", path, lineNo, lockVersion, line)
			}

			sawVersion = true
			continue
		}

		fields := strings.Fields(line)
		if len(fields) != 3 {
			return nil, fmt.Errorf("%s:%d: want `<module> <version> sha256:<hash>`, got %q", path, lineNo, line)
		}

		hash, ok := strings.CutPrefix(fields[2], "sha256:")
		if !ok {
			return nil, fmt.Errorf("%s:%d: hash must be sha256:<hex>, got %q", path, lineNo, fields[2])
		}

		host, p, ok := strings.Cut(fields[0], "/")
		if !ok {
			return nil, fmt.Errorf("%s:%d: %q must be <host>/<path>", path, lineNo, fields[0])
		}

		l.Entries[Ref{Host: host, Path: p, Version: fields[1]}] = hash
	}

	if err := sc.Err(); err != nil {
		return nil, fmt.Errorf("reading %s: %w", path, err)
	}

	return l, nil
}

// Save writes the lockfile, one line per entry, refs sorted so the file
// diffs cleanly across runs regardless of map iteration order.
func (l *Lockfile) Save(path string) error {
	refs := make([]Ref, 0, len(l.Entries))
	for r := range l.Entries {
		refs = append(refs, r)
	}

	sort.Slice(refs, func(i, j int) bool { return refs[i].String() < refs[j].String() })

	var b strings.Builder
	b.WriteString("# Generated by datasplice. Commit this file.\n")
	b.WriteString(lockVersion + "\n\n")

	for _, r := range refs {
		fmt.Fprintf(&b, "%s/%s %s sha256:%s\n", r.Host, r.Path, r.Version, l.Entries[r])
	}

	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}

	return nil
}

// Hash returns the pinned hash for ref, and whether it's present at all.
func (l *Lockfile) Hash(ref Ref) (string, bool) {
	h, ok := l.Entries[ref]
	return h, ok
}
